[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[redirects]]
  from = "/shop"
  to = "https://www.etsy.com/shop/FaintMarkDesign"

[[redirects]]
  from = "/store"
  to = "https://www.etsy.com/shop/FaintMarkDesign"

[[redirects]]
  from = "/*"
  to = "/"